p=open("hello.txt","w+")
p.write("today is great\n")
p.write("don't go you la my la\n")
p.write("rockstar i am boom boom boom\n")
p.write('ma ma one day so live a life yummm')
print(p.tell())
p.seek(0,0)
m=p.read()
print(m)